### ISSUE TITLE
When running locally, does this still upload to an online service?

### ISSUE THREAD

**Issue by still-dreaming-1** [w3c/markup-validator#17]
I'm wondering if this can run entirely locally. If I install it locally and have it test files that exist on the same machine, will it send any information to an external service, or is everything only local?

**Comment by sideshowbarker** [comment]
The checker never sends any information anywhere outside its own environment. Any information it outputs either gets sent back to the checker Web UI window from which the request was submitted (if you’re using the Web UI at all to begin with), or output to the local console/terminal or to a local log file (if you have logging configured).

So yeah if you’re running it locally, everything is local—it never sends information to any external service. There’s not even any code in the checker backend at all that you could ever accidentally enable to make it send information outside its own environment

**Comment by still-dreaming-1** [comment]
Sounds good. The other popular local tool is Tidy, which has also been recommended to use by the W3C. I know Tidy is not all about validation and it can also try to fix your code, but some people do use it for validation as well. Actually even if you are only interested in validation you could use tidy in such a way that you see validation errors as well as comparing the diff of the "fixed" code to the original such that the diff represents suggestions for how you might want to fix those errors.

Which do you think is better for local validtion, this markup-validator or tidy and what are the main differences between them?

**Comment by sideshowbarker** [comment]
> Which do you think is better for local validation, this markup-validator or tidy and what are the main differences between them?

This tool is much better for helping you catch authoring mistakes than tidy is. tidy is not intended as a validator, and it only does a very limited number of checks. This tool does a very wide variety of checks on your source—including very fine-grained checking of the attribute datatypes/microsyntax.

The purpose of this tool is to try to very hard to help you catch mistakes in your HTML source you might have otherwise missed.

**Comment by sideshowbarker** [comment]
Oh, actually I only now just realized I was commenting at a different github repo than the one I thought I had been. I thought this issue had posted at https://github.com/validator/validator/ The comments I had posted here previously apply to https://github.com/validator/validator/, not this.

I recommend you use https://github.com/validator/validator/ instead of the tool here. The code here at https://github.com/w3c/markup-validator is for the legacy validator and is no longer being actively maintained. I don’t recommend trying to run it locally. Try  https://github.com/validator/validator/.
