### ISSUE TITLE
Inverted border radius CSS technique causing thin lines in the layout on very high resolutions and on some mobile screens

### ISSUE THREAD

**Issue by UtopistList** [w3c/markup-validator#64]
To replicate, example:
https://codepen.io/jeroenknol/pen/wVeaMM

https://stackoverflow.com/questions/69946524/has-anyone-encountered-these-glitches-or-subpixel-lines-and-know-what-they-are

**Comment by dontcallmedom** [comment]
this repo is about the [W3C Markup Validator service](https://validator.w3.org/) which can't help with debugging CSS layout issues; there may be an underlying issue in [CSS specs](https://github.com/w3c/csswg-drafts/), although my guess is that it's more likely an implementation bug or a bug in the specific technique. In any case, closing this issue since it's not related to the markup validator.
